---

  - name: 'common: install python-apt'
    raw: 'apt-get install -y python-apt'
    tags: common

  - name: 'common: update apt package cache'
    apt: update_cache=yes
    tags: common

  - name: 'common: update apt'
    apt: upgrade=yes
    tags: common

  - name: 'common: install base packages'
    apt: pkg=$item state=installed
    with_items:
      - build-essential
      - python
      - python-dev
      - python-pip
      - python-virtualenv
      - git
    tags: common
