---
  - name: common | main.yml | install base packages
    apt: pkg={{ item }} state=installed update_cache=yes cache_valid_time=3600
    with_items:
      - build-essential
      - python
      - python-dev
      - python-pip
      - python-virtualenv
      - git
    tags: common
