# usage: ansible-playbook example-playbook.yml --extra-vars=""
---
- name: install flask-skeleton
  hosts: vagrant
  sudo: True
  user: vagrant
  gather_facts: False
  roles:
    - common
    - web
    - deployer
